config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :apartments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apartments_controller.rb
# frozen_string_literal: true

class ApartmentsController < ApplicationController
  layout "application"

  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  extend Trickster

  tricks HasTheme

  theme :inloco
end

app/controllers/concerns/has_theme.rb
# frozen_string_literal: true

module HasTheme
  extend ActiveSupport::Concern

  def self.included(base)
    base.class_eval do
      extend ClassMethods
    end
  end

  module ClassMethods
    extend ActionController::Helpers::ClassMethods

    def theme(theme_name)
      define_theme_helper(theme_name)
    end

    def define_theme_helper(theme_name)
      helper_method :theme_stylesheet_link_tag
      helper_method :current_theme

      define_method(:theme_stylesheet_link_tag) do
        theme_path = theme_name.to_s == 'default' ? 'application.css' : "themes/#{theme_name}.css"

        helpers.stylesheet_link_tag(
          theme_path,
          media: 'all',
          'data-turbolinks-track': 'reload',
          defer: true
        )
      end

      define_method(:current_theme) do
        theme_name
      end
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  
  def home
  	render layout: 'landing'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
# frozen_string_literal: true

module ImageHelper
  def lazy_image_attachment_tag(attachment, options)
    placeholder = attachment.url(:thumb_64)
    src = options[:version] ? attachment.url(options[:version]) : attachment.url
    class_attr = options[:class].to_s + ' lazy'

    image_tag(
      placeholder,
      options.merge(
        class: class_attr,
        id: SecureRandom.hex(10),
        data: { src: src, flickity_lazyload_src: src }
      )
    )
  end

  def avatar_url(user = nil, version = :thumb_64)
    return 'default-avatar1.png' unless user

    if user.avatar.url.present?
      user.avatar.url(version)
    elsif user.facebook_avatar.present?
      user.facebook_avatar + '?type=large'
    else
      user.female? ? 'default-avatar2.png' : 'default-avatar1.png'
    end
  end

  # Returns an image url or a fallback image for a generic resource.
  # resouce is a photo or any resource that responds to #cover, #photo or #photos
  def attachment_url(resource, version = :thumb_64)
    uploader = if resource.respond_to?(:mount_on)
                 resource
               else
                 extract_uploader(resource)
               end

    uploader.present? ? uploader.url(version) : 'no-img-fallback.png'
  end

  def extract_uploader(resource)
    return resource.attachment if resource.respond_to?(:attachment)

    if resource.respond_to?(:cover) && resource.cover.present?
      resource.cover
    elsif resource.respond_to?(:photo) && resource.photo.present?
      resource.photo
    else
      resource.photos&.first&.attachment
    end
  end
end

app/views/apartments/index.html.erb
<div class="index-div">
	<%= link_to "Apartment", apartment_path(id: 'ultra') %>
</div>

app/views/apartments/show.html.erb
<%= render Views::Apartments::BannerComponent.new %>

<%= render Bootstrap::Layouts::LevitatingSectionComponent.new sticky: { top: '0px' } do %>
  <%= render Bootstrap::Layouts::ContainerComponent.new do %>
    <%= render Bootstrap::Layouts::RowComponent.new do %>
      <%= render Bootstrap::Layouts::ColumnComponent.new breakpoints: { xs: 12, lg: 12 }, options: {} do %>
        <%= render Views::Apartments::HeaderComponent.new apartment: nil %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= render Views::Apartments::ImagesSliderComponent.new apartment: nil %>


<%= render Bootstrap::Layouts::SectionComponent.new do %>
  <%= render Bootstrap::Layouts::ContainerComponent.new do %>
    <%= render Bootstrap::Layouts::RowComponent.new do %>
      <%= render Bootstrap::Layouts::ColumnComponent.new breakpoints: { xs: 12, lg: 8 }, options: { paddings: { lg: { r:  '8' } } } do %>
        <%= render Views::Apartments::AmenitiesComponent.new apartment: nil %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= render Bootstrap::Layouts::SectionComponent.new do %>
  <%= render Bootstrap::Layouts::ContainerComponent.new do %>
    <%= render Bootstrap::Layouts::RowComponent.new do %>
      <%= render Bootstrap::Layouts::ColumnComponent.new breakpoints: { xs: 12, lg: 12 }, options: { paddings: { lg: { r:  '8' } } } do %>
        <%= render Views::Apartments::GoogleMapComponent.new apartment: nil %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<footer class="wrapper bg-dark text-white pt-10 mt-10">
  <section class="container">
    <div class="row d-flex">
      <div class="col-md-8 col-sm-12 logo-wrapper">
        <div class="mb-4">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', height:"100px" %>
          <% end %>
        </div>

        <div class="pl-4">
          <div class="col-md-6 col-sm-6 pl-0 mb-3">
            <form>
              <%= text_field_tag 'email', '', class: 'form-control required email border-white bg-transparent text-white border-top-0 remove-focus border-left-0 border-right-0 rounded-0' %>
            </form>
          </div>
        </div>

        <div class="pl-1 mb-3">
          <span class="copyright ml-0 ml-lg-4 d-block">&copy; <%= Time.zone.today.year %> June Properties
        </div>
      </div>

      <div class="col-md-4 col-sm-12 my-3">

        <div class="pt-6 pb-3 address">
          <span class="py-3">Contact</span><br>
          <span class="text-justify">
            +320123456 
            <br />
            Boulevard Saint-Miche l47,1040 ETTERBEEK
          </span>
        </div>
        <div class="pt-6 pb-3 social-icon">
          <div class="">
            <%= link_to "https://wa.me/32499319337", target: :blank, class: 'text-decoration-none lead px-2 text-white' do %>
              <%= inline_svg 'social/whatsapp.svg', class: 'icon icon-white icon-sm' %>
            <% end %>
            <%= link_to "https://www.facebook.com/ColocHousing/", target: :blan, class: 'text-decoration-none lead px-2 text-white' do %>
              <%= inline_svg 'social/facebook.svg', class: 'icon icon-white icon-sm' %>
            <% end %>
            <%= link_to "http://linkedin.com/company/colochousing/", target: :blank, class: 'text-decoration-none lead px-2 text-white' do %>
              <%= inline_svg 'social/linkedin.svg', class: 'icon icon-white icon-sm' %>
            <% end %>
            <%= link_to "https://www.instagram.com/colochousing/", target: :blank, class: 'text-decoration-none lead px-2 text-white' do %>
              <%= inline_svg 'social/instagram.svg', class: 'icon icon-white icon-sm' %>
            <% end %>
            <%= link_to "https://www.twitter.com/colochousing/", target: :blank, class: 'text-decoration-none lead px-2 text-white' do %>
              <%= inline_svg 'social/twitter.svg', class: 'icon icon-white icon-sm' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/application/_head.html.erb
<head>
  <%= render 'meta-tags' %>
  <%= render 'favicon' %>

  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= theme_stylesheet_link_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}", 'data-turbolinks-eval': false %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# javascript_include_tag 'https://static.zdassets.com/ekr/snippet.js?key=38971158-c741-45a1-bb4c-bbc37ec29308', id: 'ze-snippet' %>
</head>

app/views/application/_meta-tags.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

<%= display_meta_tags(
      site: 'juneproperties',
      title: 'Furnished Apartments near EU institutions',
      description: 'We offer you three recently renovated apartments at Rue de Spa 32 with parking and 24/7 property assistance included.',
      keywords: 'june properties',
      og: {
        card: 'summary',
        site: '@juneproperties',
        creator: '@juneproperties',
        url: 'http://www.juneproperties.be',
        title: 'Furnished Apartments near EU institutions',
        description: 'We offer you three recently renovated apartments at Rue de Spa 32 with parking and 24/7 property assistance included.'
      },
      twitter: {
        title: 'Furnished Apartments near EU institutions',
        description: 'We offer you three recently renovated apartments at Rue de Spa 32 with parking and 24/7 property assistance included.',
        image: image_url('seo.jpg'),
        type: 'website',
        url: 'http://www.juneproperties.be'
      }
    ) %>

<%= yield :meta_tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xml:lang="<%= I18n.locale || 'en' %>" lang="<%= I18n.locale || 'en'%>">
  <%= render 'head' %>

  <body
    class="<%= params[:locale] ||= 'en' %>"
    data-controller="page <%= yield :stimulus_controller if content_for? :stimulus_controller %>"
    <%= yield :data_attributes %>
  >
    <%= render Views::Static::NavBarComponent.new %>
    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juneproperties</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'meta-tags' %>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing-page">
  <%= render Views::Static::VirtualTourComponent.new %>
  <div class="logo">
  	<button class="btn btn-primary px-5 landing-page-button border-0" onclick=" window.open('https://www.facebook.com/junepropertiesbelgium','_blank')">
      <%= image_tag 'logo.png', width:"260px" %>
    </button>
  </div>
  <button class="btn btn-primary px-5 landing-page-button" onclick=" window.open('https://calendly.com/juneproperties','_blank')"> Book a Visit</button>
</div>